#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
staged_files=$(git diff --cached --name-only)
echo "[pre-commit] Running pre-commit hook"
echo "[pre-commit] Formatting frontend code"
cd client
npx eslint --fix src vite.config.js eslint.config.js
prettier src vite.config.js eslint.config.js --print-width 100 -w
echo "[pre-commit] Formatting backend code"
cd ../server
isort app
black app -l 100
cd ..
echo "[pre-commit] Staging formatted files"
git add ${staged_files[@]}
echo "[pre-commit] Done"
